// flow-typed signature: 16c73ed9231c5ad37bbc5a975336f7ee
// flow-typed version: <<STUB>>/amd-loader_v^0.0.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amd-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'amd-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amd-loader/amd-loader' {
  declare module.exports: any;
}

declare module 'amd-loader/test/node_modules/a' {
  declare module.exports: any;
}

declare module 'amd-loader/test/node_modules/b' {
  declare module.exports: any;
}

declare module 'amd-loader/test/node_modules/d' {
  declare module.exports: any;
}

declare module 'amd-loader/test/node_modules/e' {
  declare module.exports: any;
}

declare module 'amd-loader/test/test' {
  declare module.exports: any;
}

declare module 'amd-loader/test/test2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amd-loader/amd-loader.js' {
  declare module.exports: $Exports<'amd-loader/amd-loader'>;
}
declare module 'amd-loader/test/node_modules/a.js' {
  declare module.exports: $Exports<'amd-loader/test/node_modules/a'>;
}
declare module 'amd-loader/test/node_modules/b.js' {
  declare module.exports: $Exports<'amd-loader/test/node_modules/b'>;
}
declare module 'amd-loader/test/node_modules/d.js' {
  declare module.exports: $Exports<'amd-loader/test/node_modules/d'>;
}
declare module 'amd-loader/test/node_modules/e.js' {
  declare module.exports: $Exports<'amd-loader/test/node_modules/e'>;
}
declare module 'amd-loader/test/test.js' {
  declare module.exports: $Exports<'amd-loader/test/test'>;
}
declare module 'amd-loader/test/test2.js' {
  declare module.exports: $Exports<'amd-loader/test/test2'>;
}
