// flow-typed signature: 4a345bfe377853b6fc4a19d73d437461
// flow-typed version: <<STUB>>/ansi-colorizer_v^1.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-colorizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-colorizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ansi-colorizer/autolint' {
  declare module.exports: any;
}

declare module 'ansi-colorizer/buster' {
  declare module.exports: any;
}

declare module 'ansi-colorizer/lib/ansi-colorizer' {
  declare module.exports: any;
}

declare module 'ansi-colorizer/run-tests' {
  declare module.exports: any;
}

declare module 'ansi-colorizer/test/ansi-colorizer-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ansi-colorizer/autolint.js' {
  declare module.exports: $Exports<'ansi-colorizer/autolint'>;
}
declare module 'ansi-colorizer/buster.js' {
  declare module.exports: $Exports<'ansi-colorizer/buster'>;
}
declare module 'ansi-colorizer/lib/ansi-colorizer.js' {
  declare module.exports: $Exports<'ansi-colorizer/lib/ansi-colorizer'>;
}
declare module 'ansi-colorizer/run-tests.js' {
  declare module.exports: $Exports<'ansi-colorizer/run-tests'>;
}
declare module 'ansi-colorizer/test/ansi-colorizer-test.js' {
  declare module.exports: $Exports<'ansi-colorizer/test/ansi-colorizer-test'>;
}
