// flow-typed signature: ea02762c8e921d7304a9332f4b0d1ce6
// flow-typed version: <<STUB>>/babel-plugin-minify-dead-code-elimination_v^0.1.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-minify-dead-code-elimination'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-minify-dead-code-elimination' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-minify-dead-code-elimination/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-minify-dead-code-elimination/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-minify-dead-code-elimination/lib/index'>;
}
