// flow-typed signature: 599c0da6e4bbc5c6f0e5ec259116a939
// flow-typed version: <<STUB>>/child-process-data_v^0.5.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'child-process-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'child-process-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'child-process-data/gulp/build' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/clean' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/dist' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/globs' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/gulpfiles' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/prepublish' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/tdd' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/test' {
  declare module.exports: any;
}

declare module 'child-process-data/gulp/watch' {
  declare module.exports: any;
}

declare module 'child-process-data/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/check-child-process' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/child-process-data' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/extend-options' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/index' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-data-callbacks' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-io-test' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-on-close-callback' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-on-data-callback' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-options' {
  declare module.exports: any;
}

declare module 'child-process-data/lib/make-single-test' {
  declare module.exports: any;
}

declare module 'child-process-data/src/check-child-process' {
  declare module.exports: any;
}

declare module 'child-process-data/src/child-process-data' {
  declare module.exports: any;
}

declare module 'child-process-data/src/extend-options' {
  declare module.exports: any;
}

declare module 'child-process-data/src/index' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-data-callbacks' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-io-test' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-on-close-callback' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-on-data-callback' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-options' {
  declare module.exports: any;
}

declare module 'child-process-data/src/make-single-test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/child-process-data.test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/examples.test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/examples/error-exit' {
  declare module.exports: any;
}

declare module 'child-process-data/test/examples/normal-exit' {
  declare module.exports: any;
}

declare module 'child-process-data/test/forget.test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/gulpfiles/gulpfile_gulp-error_plumber' {
  declare module.exports: any;
}

declare module 'child-process-data/test/gulpfiles/gulpfile_gulp-error' {
  declare module.exports: any;
}

declare module 'child-process-data/test/gulpfiles/gulpfile_gutil.log' {
  declare module.exports: any;
}

declare module 'child-process-data/test/gulpfiles/gulpfile_single-test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/io/readline' {
  declare module.exports: any;
}

declare module 'child-process-data/test/make-io-test.test' {
  declare module.exports: any;
}

declare module 'child-process-data/test/make-single-test.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'child-process-data/gulp/build.js' {
  declare module.exports: $Exports<'child-process-data/gulp/build'>;
}
declare module 'child-process-data/gulp/clean.js' {
  declare module.exports: $Exports<'child-process-data/gulp/clean'>;
}
declare module 'child-process-data/gulp/dist.js' {
  declare module.exports: $Exports<'child-process-data/gulp/dist'>;
}
declare module 'child-process-data/gulp/globs.js' {
  declare module.exports: $Exports<'child-process-data/gulp/globs'>;
}
declare module 'child-process-data/gulp/gulpfiles.js' {
  declare module.exports: $Exports<'child-process-data/gulp/gulpfiles'>;
}
declare module 'child-process-data/gulp/prepublish.js' {
  declare module.exports: $Exports<'child-process-data/gulp/prepublish'>;
}
declare module 'child-process-data/gulp/tdd.js' {
  declare module.exports: $Exports<'child-process-data/gulp/tdd'>;
}
declare module 'child-process-data/gulp/test.js' {
  declare module.exports: $Exports<'child-process-data/gulp/test'>;
}
declare module 'child-process-data/gulp/watch.js' {
  declare module.exports: $Exports<'child-process-data/gulp/watch'>;
}
declare module 'child-process-data/gulpfile.babel.js' {
  declare module.exports: $Exports<'child-process-data/gulpfile.babel'>;
}
declare module 'child-process-data/lib/check-child-process.js' {
  declare module.exports: $Exports<'child-process-data/lib/check-child-process'>;
}
declare module 'child-process-data/lib/child-process-data.js' {
  declare module.exports: $Exports<'child-process-data/lib/child-process-data'>;
}
declare module 'child-process-data/lib/extend-options.js' {
  declare module.exports: $Exports<'child-process-data/lib/extend-options'>;
}
declare module 'child-process-data/lib/index.js' {
  declare module.exports: $Exports<'child-process-data/lib/index'>;
}
declare module 'child-process-data/lib/make-data-callbacks.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-data-callbacks'>;
}
declare module 'child-process-data/lib/make-io-test.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-io-test'>;
}
declare module 'child-process-data/lib/make-on-close-callback.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-on-close-callback'>;
}
declare module 'child-process-data/lib/make-on-data-callback.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-on-data-callback'>;
}
declare module 'child-process-data/lib/make-options.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-options'>;
}
declare module 'child-process-data/lib/make-single-test.js' {
  declare module.exports: $Exports<'child-process-data/lib/make-single-test'>;
}
declare module 'child-process-data/src/check-child-process.js' {
  declare module.exports: $Exports<'child-process-data/src/check-child-process'>;
}
declare module 'child-process-data/src/child-process-data.js' {
  declare module.exports: $Exports<'child-process-data/src/child-process-data'>;
}
declare module 'child-process-data/src/extend-options.js' {
  declare module.exports: $Exports<'child-process-data/src/extend-options'>;
}
declare module 'child-process-data/src/index.js' {
  declare module.exports: $Exports<'child-process-data/src/index'>;
}
declare module 'child-process-data/src/make-data-callbacks.js' {
  declare module.exports: $Exports<'child-process-data/src/make-data-callbacks'>;
}
declare module 'child-process-data/src/make-io-test.js' {
  declare module.exports: $Exports<'child-process-data/src/make-io-test'>;
}
declare module 'child-process-data/src/make-on-close-callback.js' {
  declare module.exports: $Exports<'child-process-data/src/make-on-close-callback'>;
}
declare module 'child-process-data/src/make-on-data-callback.js' {
  declare module.exports: $Exports<'child-process-data/src/make-on-data-callback'>;
}
declare module 'child-process-data/src/make-options.js' {
  declare module.exports: $Exports<'child-process-data/src/make-options'>;
}
declare module 'child-process-data/src/make-single-test.js' {
  declare module.exports: $Exports<'child-process-data/src/make-single-test'>;
}
declare module 'child-process-data/test/child-process-data.test.js' {
  declare module.exports: $Exports<'child-process-data/test/child-process-data.test'>;
}
declare module 'child-process-data/test/examples.test.js' {
  declare module.exports: $Exports<'child-process-data/test/examples.test'>;
}
declare module 'child-process-data/test/examples/error-exit.js' {
  declare module.exports: $Exports<'child-process-data/test/examples/error-exit'>;
}
declare module 'child-process-data/test/examples/normal-exit.js' {
  declare module.exports: $Exports<'child-process-data/test/examples/normal-exit'>;
}
declare module 'child-process-data/test/forget.test.js' {
  declare module.exports: $Exports<'child-process-data/test/forget.test'>;
}
declare module 'child-process-data/test/gulpfiles/gulpfile_gulp-error_plumber.js' {
  declare module.exports: $Exports<'child-process-data/test/gulpfiles/gulpfile_gulp-error_plumber'>;
}
declare module 'child-process-data/test/gulpfiles/gulpfile_gulp-error.js' {
  declare module.exports: $Exports<'child-process-data/test/gulpfiles/gulpfile_gulp-error'>;
}
declare module 'child-process-data/test/gulpfiles/gulpfile_gutil.log.js' {
  declare module.exports: $Exports<'child-process-data/test/gulpfiles/gulpfile_gutil.log'>;
}
declare module 'child-process-data/test/gulpfiles/gulpfile_single-test.js' {
  declare module.exports: $Exports<'child-process-data/test/gulpfiles/gulpfile_single-test'>;
}
declare module 'child-process-data/test/io/readline.js' {
  declare module.exports: $Exports<'child-process-data/test/io/readline'>;
}
declare module 'child-process-data/test/make-io-test.test.js' {
  declare module.exports: $Exports<'child-process-data/test/make-io-test.test'>;
}
declare module 'child-process-data/test/make-single-test.test.js' {
  declare module.exports: $Exports<'child-process-data/test/make-single-test.test'>;
}
