// flow-typed signature: c0c028f592a2ef4669cf8ef880aab292
// flow-typed version: <<STUB>>/flat-map_v^0.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flat-map/flat-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flat-map/flat-map.js' {
  declare module.exports: $Exports<'flat-map/flat-map'>;
}
