// flow-typed signature: 6ed700bfda84183b3d2a3f37e0c7f8e7
// flow-typed version: <<STUB>>/fs-es6-promise_v^0.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-es6-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-es6-promise/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-es6-promise/index' {
  declare module.exports: $Exports<'fs-es6-promise'>;
}
declare module 'fs-es6-promise/index.js' {
  declare module.exports: $Exports<'fs-es6-promise'>;
}
declare module 'fs-es6-promise/test.js' {
  declare module.exports: $Exports<'fs-es6-promise/test'>;
}
