// flow-typed signature: 72e5c8a09803bddb39f07d3338a5c657
// flow-typed version: <<STUB>>/glup_v^1.0.14/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glup/glup' {
  declare module.exports: any;
}

declare module 'glup/libs/build' {
  declare module.exports: any;
}

declare module 'glup/libs/defaults' {
  declare module.exports: any;
}

declare module 'glup/libs/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glup/glup.js' {
  declare module.exports: $Exports<'glup/glup'>;
}
declare module 'glup/libs/build.js' {
  declare module.exports: $Exports<'glup/libs/build'>;
}
declare module 'glup/libs/defaults.js' {
  declare module.exports: $Exports<'glup/libs/defaults'>;
}
declare module 'glup/libs/plugins.js' {
  declare module.exports: $Exports<'glup/libs/plugins'>;
}
