// flow-typed signature: 59847959c45806026eb78c356b78b5d6
// flow-typed version: <<STUB>>/gulp-webpack_v^1.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-webpack/index' {
  declare module.exports: $Exports<'gulp-webpack'>;
}
declare module 'gulp-webpack/index.js' {
  declare module.exports: $Exports<'gulp-webpack'>;
}
