// flow-typed signature: c84bf6e21663915c9dc379bfddcdba1d
// flow-typed version: <<STUB>>/gulp-antlr4_v^0.3.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-antlr4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-antlr4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-antlr4/gulp/build' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/clean' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/dist' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/distclean' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/doc' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/lint' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/prepublish' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/tdd' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/test' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulp/watch' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/lib/gulp-antlr4' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/src/gulp-antlr4' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/test/gulp-antlr4.test' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/test/gulpfiles/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/test/helpers' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/test/sources/EvalVisitor' {
  declare module.exports: any;
}

declare module 'gulp-antlr4/test/sources/ShortToUnicodeString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-antlr4/gulp/build.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/build'>;
}
declare module 'gulp-antlr4/gulp/clean.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/clean'>;
}
declare module 'gulp-antlr4/gulp/dist.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/dist'>;
}
declare module 'gulp-antlr4/gulp/distclean.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/distclean'>;
}
declare module 'gulp-antlr4/gulp/doc.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/doc'>;
}
declare module 'gulp-antlr4/gulp/lint.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/lint'>;
}
declare module 'gulp-antlr4/gulp/prepublish.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/prepublish'>;
}
declare module 'gulp-antlr4/gulp/tdd.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/tdd'>;
}
declare module 'gulp-antlr4/gulp/test.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/test'>;
}
declare module 'gulp-antlr4/gulp/watch.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulp/watch'>;
}
declare module 'gulp-antlr4/gulpfile.babel.js' {
  declare module.exports: $Exports<'gulp-antlr4/gulpfile.babel'>;
}
declare module 'gulp-antlr4/lib/gulp-antlr4.js' {
  declare module.exports: $Exports<'gulp-antlr4/lib/gulp-antlr4'>;
}
declare module 'gulp-antlr4/src/gulp-antlr4.js' {
  declare module.exports: $Exports<'gulp-antlr4/src/gulp-antlr4'>;
}
declare module 'gulp-antlr4/test/gulp-antlr4.test.js' {
  declare module.exports: $Exports<'gulp-antlr4/test/gulp-antlr4.test'>;
}
declare module 'gulp-antlr4/test/gulpfiles/gulpfile.babel.js' {
  declare module.exports: $Exports<'gulp-antlr4/test/gulpfiles/gulpfile.babel'>;
}
declare module 'gulp-antlr4/test/helpers.js' {
  declare module.exports: $Exports<'gulp-antlr4/test/helpers'>;
}
declare module 'gulp-antlr4/test/sources/EvalVisitor.js' {
  declare module.exports: $Exports<'gulp-antlr4/test/sources/EvalVisitor'>;
}
declare module 'gulp-antlr4/test/sources/ShortToUnicodeString.js' {
  declare module.exports: $Exports<'gulp-antlr4/test/sources/ShortToUnicodeString'>;
}
