// flow-typed signature: 3e12fc99cab5cb5aab1c6efa2b264e13
// flow-typed version: <<STUB>>/gulp-file_v^0.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-file/lib/file' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-file/lib/file.js' {
  declare module.exports: $Exports<'gulp-file/lib/file'>;
}
