// flow-typed signature: 4a390ddbfd6271dea855183388b498b4
// flow-typed version: <<STUB>>/gulp-combine_v^0.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-combine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-combine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-combine/example/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-combine/example/src/main' {
  declare module.exports: any;
}

declare module 'gulp-combine/example/src/util/add' {
  declare module.exports: any;
}

declare module 'gulp-combine/example/src/util/mathUtil' {
  declare module.exports: any;
}

declare module 'gulp-combine/moduleManager' {
  declare module.exports: any;
}

declare module 'gulp-combine/test/main' {
  declare module.exports: any;
}

declare module 'gulp-combine/test/sampleSourceFiles/anotherModule' {
  declare module.exports: any;
}

declare module 'gulp-combine/test/sampleSourceFiles/mainModule' {
  declare module.exports: any;
}

declare module 'gulp-combine/test/sampleSourceFiles/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-combine/example/gulpfile.js' {
  declare module.exports: $Exports<'gulp-combine/example/gulpfile'>;
}
declare module 'gulp-combine/example/src/main.js' {
  declare module.exports: $Exports<'gulp-combine/example/src/main'>;
}
declare module 'gulp-combine/example/src/util/add.js' {
  declare module.exports: $Exports<'gulp-combine/example/src/util/add'>;
}
declare module 'gulp-combine/example/src/util/mathUtil.js' {
  declare module.exports: $Exports<'gulp-combine/example/src/util/mathUtil'>;
}
declare module 'gulp-combine/index' {
  declare module.exports: $Exports<'gulp-combine'>;
}
declare module 'gulp-combine/index.js' {
  declare module.exports: $Exports<'gulp-combine'>;
}
declare module 'gulp-combine/moduleManager.js' {
  declare module.exports: $Exports<'gulp-combine/moduleManager'>;
}
declare module 'gulp-combine/test/main.js' {
  declare module.exports: $Exports<'gulp-combine/test/main'>;
}
declare module 'gulp-combine/test/sampleSourceFiles/anotherModule.js' {
  declare module.exports: $Exports<'gulp-combine/test/sampleSourceFiles/anotherModule'>;
}
declare module 'gulp-combine/test/sampleSourceFiles/mainModule.js' {
  declare module.exports: $Exports<'gulp-combine/test/sampleSourceFiles/mainModule'>;
}
declare module 'gulp-combine/test/sampleSourceFiles/util.js' {
  declare module.exports: $Exports<'gulp-combine/test/sampleSourceFiles/util'>;
}
