// flow-typed signature: 6f2b9ed7a5c6dbfaa32107d5aed431f2
// flow-typed version: <<STUB>>/gulp-download_v^0.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-download/index' {
  declare module.exports: $Exports<'gulp-download'>;
}
declare module 'gulp-download/index.js' {
  declare module.exports: $Exports<'gulp-download'>;
}
