// flow-typed signature: 4a3a47a72865be45e219d0623d1be1bd
// flow-typed version: <<STUB>>/gulp-sequence_v^0.4.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-sequence/index' {
  declare module.exports: $Exports<'gulp-sequence'>;
}
declare module 'gulp-sequence/index.js' {
  declare module.exports: $Exports<'gulp-sequence'>;
}
