// flow-typed signature: 28d299088c203a40b3739ace4f509695
// flow-typed version: <<STUB>>/gulp-webserver_v^0.9.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-webserver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-webserver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-webserver/src/enableMiddlewareShorthand/index' {
  declare module.exports: any;
}

declare module 'gulp-webserver/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-webserver/src/enableMiddlewareShorthand/index.js' {
  declare module.exports: $Exports<'gulp-webserver/src/enableMiddlewareShorthand/index'>;
}
declare module 'gulp-webserver/src/index.js' {
  declare module.exports: $Exports<'gulp-webserver/src/index'>;
}
