// flow-typed signature: c201451e7c9819963e03386b20370276
// flow-typed version: <<STUB>>/map-stream_v^0.0.7/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'map-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'map-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'map-stream/examples/pretty' {
  declare module.exports: any;
}

declare module 'map-stream/test/simple-map.asynct' {
  declare module.exports: any;
}

// Filename aliases
declare module 'map-stream/examples/pretty.js' {
  declare module.exports: $Exports<'map-stream/examples/pretty'>;
}
declare module 'map-stream/index' {
  declare module.exports: $Exports<'map-stream'>;
}
declare module 'map-stream/index.js' {
  declare module.exports: $Exports<'map-stream'>;
}
declare module 'map-stream/test/simple-map.asynct.js' {
  declare module.exports: $Exports<'map-stream/test/simple-map.asynct'>;
}
