// flow-typed signature: 235721e484693fcd420093219c040f7d
// flow-typed version: <<STUB>>/wu_v^2.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wu/assert' {
  declare module.exports: any;
}

declare module 'wu/dist/wu.debug' {
  declare module.exports: any;
}

declare module 'wu/dist/wu' {
  declare module.exports: any;
}

declare module 'wu/dist/wu.min' {
  declare module.exports: any;
}

declare module 'wu/test/test-asyncEach' {
  declare module.exports: any;
}

declare module 'wu/test/test-chain' {
  declare module.exports: any;
}

declare module 'wu/test/test-chunk' {
  declare module.exports: any;
}

declare module 'wu/test/test-concatMap' {
  declare module.exports: any;
}

declare module 'wu/test/test-count' {
  declare module.exports: any;
}

declare module 'wu/test/test-curryable' {
  declare module.exports: any;
}

declare module 'wu/test/test-cycle' {
  declare module.exports: any;
}

declare module 'wu/test/test-drop' {
  declare module.exports: any;
}

declare module 'wu/test/test-dropWhile' {
  declare module.exports: any;
}

declare module 'wu/test/test-entries' {
  declare module.exports: any;
}

declare module 'wu/test/test-enumerate' {
  declare module.exports: any;
}

declare module 'wu/test/test-every' {
  declare module.exports: any;
}

declare module 'wu/test/test-filter' {
  declare module.exports: any;
}

declare module 'wu/test/test-find' {
  declare module.exports: any;
}

declare module 'wu/test/test-flatten' {
  declare module.exports: any;
}

declare module 'wu/test/test-forEach' {
  declare module.exports: any;
}

declare module 'wu/test/test-has' {
  declare module.exports: any;
}

declare module 'wu/test/test-invoke' {
  declare module.exports: any;
}

declare module 'wu/test/test-keys' {
  declare module.exports: any;
}

declare module 'wu/test/test-map' {
  declare module.exports: any;
}

declare module 'wu/test/test-pluck' {
  declare module.exports: any;
}

declare module 'wu/test/test-reduce' {
  declare module.exports: any;
}

declare module 'wu/test/test-reductions' {
  declare module.exports: any;
}

declare module 'wu/test/test-reject' {
  declare module.exports: any;
}

declare module 'wu/test/test-repeat' {
  declare module.exports: any;
}

declare module 'wu/test/test-slice' {
  declare module.exports: any;
}

declare module 'wu/test/test-some' {
  declare module.exports: any;
}

declare module 'wu/test/test-spreadMap' {
  declare module.exports: any;
}

declare module 'wu/test/test-take' {
  declare module.exports: any;
}

declare module 'wu/test/test-takeWhile' {
  declare module.exports: any;
}

declare module 'wu/test/test-tap' {
  declare module.exports: any;
}

declare module 'wu/test/test-tee' {
  declare module.exports: any;
}

declare module 'wu/test/test-unique' {
  declare module.exports: any;
}

declare module 'wu/test/test-unzip' {
  declare module.exports: any;
}

declare module 'wu/test/test-values' {
  declare module.exports: any;
}

declare module 'wu/test/test-zip' {
  declare module.exports: any;
}

declare module 'wu/test/test-zipLongest' {
  declare module.exports: any;
}

declare module 'wu/test/test-zipWith' {
  declare module.exports: any;
}

declare module 'wu/webpack.config' {
  declare module.exports: any;
}

declare module 'wu/wu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wu/assert.js' {
  declare module.exports: $Exports<'wu/assert'>;
}
declare module 'wu/dist/wu.debug.js' {
  declare module.exports: $Exports<'wu/dist/wu.debug'>;
}
declare module 'wu/dist/wu.js' {
  declare module.exports: $Exports<'wu/dist/wu'>;
}
declare module 'wu/dist/wu.min.js' {
  declare module.exports: $Exports<'wu/dist/wu.min'>;
}
declare module 'wu/test/test-asyncEach.js' {
  declare module.exports: $Exports<'wu/test/test-asyncEach'>;
}
declare module 'wu/test/test-chain.js' {
  declare module.exports: $Exports<'wu/test/test-chain'>;
}
declare module 'wu/test/test-chunk.js' {
  declare module.exports: $Exports<'wu/test/test-chunk'>;
}
declare module 'wu/test/test-concatMap.js' {
  declare module.exports: $Exports<'wu/test/test-concatMap'>;
}
declare module 'wu/test/test-count.js' {
  declare module.exports: $Exports<'wu/test/test-count'>;
}
declare module 'wu/test/test-curryable.js' {
  declare module.exports: $Exports<'wu/test/test-curryable'>;
}
declare module 'wu/test/test-cycle.js' {
  declare module.exports: $Exports<'wu/test/test-cycle'>;
}
declare module 'wu/test/test-drop.js' {
  declare module.exports: $Exports<'wu/test/test-drop'>;
}
declare module 'wu/test/test-dropWhile.js' {
  declare module.exports: $Exports<'wu/test/test-dropWhile'>;
}
declare module 'wu/test/test-entries.js' {
  declare module.exports: $Exports<'wu/test/test-entries'>;
}
declare module 'wu/test/test-enumerate.js' {
  declare module.exports: $Exports<'wu/test/test-enumerate'>;
}
declare module 'wu/test/test-every.js' {
  declare module.exports: $Exports<'wu/test/test-every'>;
}
declare module 'wu/test/test-filter.js' {
  declare module.exports: $Exports<'wu/test/test-filter'>;
}
declare module 'wu/test/test-find.js' {
  declare module.exports: $Exports<'wu/test/test-find'>;
}
declare module 'wu/test/test-flatten.js' {
  declare module.exports: $Exports<'wu/test/test-flatten'>;
}
declare module 'wu/test/test-forEach.js' {
  declare module.exports: $Exports<'wu/test/test-forEach'>;
}
declare module 'wu/test/test-has.js' {
  declare module.exports: $Exports<'wu/test/test-has'>;
}
declare module 'wu/test/test-invoke.js' {
  declare module.exports: $Exports<'wu/test/test-invoke'>;
}
declare module 'wu/test/test-keys.js' {
  declare module.exports: $Exports<'wu/test/test-keys'>;
}
declare module 'wu/test/test-map.js' {
  declare module.exports: $Exports<'wu/test/test-map'>;
}
declare module 'wu/test/test-pluck.js' {
  declare module.exports: $Exports<'wu/test/test-pluck'>;
}
declare module 'wu/test/test-reduce.js' {
  declare module.exports: $Exports<'wu/test/test-reduce'>;
}
declare module 'wu/test/test-reductions.js' {
  declare module.exports: $Exports<'wu/test/test-reductions'>;
}
declare module 'wu/test/test-reject.js' {
  declare module.exports: $Exports<'wu/test/test-reject'>;
}
declare module 'wu/test/test-repeat.js' {
  declare module.exports: $Exports<'wu/test/test-repeat'>;
}
declare module 'wu/test/test-slice.js' {
  declare module.exports: $Exports<'wu/test/test-slice'>;
}
declare module 'wu/test/test-some.js' {
  declare module.exports: $Exports<'wu/test/test-some'>;
}
declare module 'wu/test/test-spreadMap.js' {
  declare module.exports: $Exports<'wu/test/test-spreadMap'>;
}
declare module 'wu/test/test-take.js' {
  declare module.exports: $Exports<'wu/test/test-take'>;
}
declare module 'wu/test/test-takeWhile.js' {
  declare module.exports: $Exports<'wu/test/test-takeWhile'>;
}
declare module 'wu/test/test-tap.js' {
  declare module.exports: $Exports<'wu/test/test-tap'>;
}
declare module 'wu/test/test-tee.js' {
  declare module.exports: $Exports<'wu/test/test-tee'>;
}
declare module 'wu/test/test-unique.js' {
  declare module.exports: $Exports<'wu/test/test-unique'>;
}
declare module 'wu/test/test-unzip.js' {
  declare module.exports: $Exports<'wu/test/test-unzip'>;
}
declare module 'wu/test/test-values.js' {
  declare module.exports: $Exports<'wu/test/test-values'>;
}
declare module 'wu/test/test-zip.js' {
  declare module.exports: $Exports<'wu/test/test-zip'>;
}
declare module 'wu/test/test-zipLongest.js' {
  declare module.exports: $Exports<'wu/test/test-zipLongest'>;
}
declare module 'wu/test/test-zipWith.js' {
  declare module.exports: $Exports<'wu/test/test-zipWith'>;
}
declare module 'wu/webpack.config.js' {
  declare module.exports: $Exports<'wu/webpack.config'>;
}
declare module 'wu/wu.js' {
  declare module.exports: $Exports<'wu/wu'>;
}
